language: go

services:
  - redis-server

before_install:
  - go get -t -v ./...

script:
  - go test -v -race -timeout 60m -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)